language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - RUST_BACKTRACE=1 cargo test --verbose
sudo: false
matrix:
  allow_failures:
    - rust: nightly
